# Generated by Django 5.1.2 on 2025-04-04 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='Student_name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='course_name',
        ),
    ]
